/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /Volumes/C/Documentos C/Trabajos/LQON (Lo quieras o no)/metro 3D/exportados gLTF/pared.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("../models/pared.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pared.geometry}
        material={materials["baked.pared"]}
        position={[0, 9.5, -10]}
      />
    </group>
  );
}

useGLTF.preload("/pared.glb");
